# Faça um programa que leia um numero inteiro qualquer e mostre a sua tabuada na tela
t1 = int(input('Digite um numero para ver sua tabuada:'))
#print('A sua tabuada é: \n {} \n {} \n {} \n {} \n {} \n {} \n {} \n {} \n {} \n {} '.format(t1 * 1, t1 * 2, t1 * 3, t1 * 4, t1 * 5, t1 * 6, t1 * 7, t1 * 8, t1 * 9, t1 * 10 ))
print('-' * 12)
print('{} x {:2} = {}'.format(t1, 1, t1 * 1))
print('{} x {:2} = {}'.format(t1, 2, t1* 2))
print('{} x {:2} = {}'.format(t1, 3, t1 * 3))
print('{} x {:2} = {}'.format(t1, 4, t1 * 4))
print('{} x {:2} = {}'.format(t1, 5, t1 * 5))
print('{} x {:2} = {}'.format(t1, 6, t1 * 6))
print('{} x {:2} = {}'.format(t1, 7, t1 * 7))
print('{} x {:2} = {}'.format(t1, 8, t1 * 8))
print('{} x {:2} = {}'.format(t1, 9, t1 * 9))
print('{} x {:2} = {}'.format(t1, 10,t1* 10))
print('-' *12 )